### ISSUE TITLE
컴포넌트 별 역할 구성 및 상태 정보 정리

### ISSUE THREAD

**Issue by gidoldory** [codestates-seb/seb41_main_027#43]
### 어떤 기능을 만들 것인가요?
- wireframe을 토대로 컴포넌트 역할 및 상태 정보 정의
- 모달위주의 UI기 때문에 상태 정보를 잘 정리해야 개발 분배작업이 원활하다.(멘토 조언)

### 기능을 만들기 위해 무엇을 해야 하나요?
- [ ] 1. 컴포넌트 구성 및 역할, props 및 지역/전역 상태 정보 정리
- [x] 2. page/modal css z-index 정리

**Comment by SpringintheFall** [comment]
[컴포넌트 리스트/구글 공유 시트](https://docs.google.com/spreadsheets/d/1jf6AX-EaPvgHMNs9zgsZ-7fpfQqd1LgSeNunZm8yHbo/edit#gid=0)
